export async function exportDocumentAsPDF(
  documentContent: string,
  documentType: string,
  generatedDate: string,
  dealId?: number
): Promise<void> {
  const html2pdfModule = await import('html2pdf.js')
  const html2pdf = html2pdfModule.default

  const today = generatedDate || new Date().toISOString().split('T')[0]
  const docType = documentType.toUpperCase()
  const referenceNumber = dealId ? `DEAL-${dealId}` : 'REFERENCE'

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <style>
        * { margin: 0; padding: 0; }
        body {
          font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
          line-height: 1.6;
          color: #333;
          background: white;
        }
        .page-break { page-break-after: always; }
        .header {
          text-align: center;
          border-bottom: 3px solid #2c3e50;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .company-name {
          font-size: 24px;
          font-weight: bold;
          color: #2c3e50;
          margin-bottom: 5px;
        }
        .company-tagline {
          font-size: 12px;
          color: #7f8c8d;
          letter-spacing: 1px;
        }
        .document-header {
          margin-bottom: 30px;
          background: #f8f9fa;
          padding: 20px;
          border-left: 4px solid #3498db;
        }
        .doc-type {
          font-size: 18px;
          font-weight: bold;
          color: #2c3e50;
          margin-bottom: 10px;
        }
        .doc-meta {
          font-size: 12px;
          color: #555;
          line-height: 1.8;
        }
        .doc-meta-label {
          font-weight: bold;
          color: #333;
        }
        .document-body {
          padding: 20px 0;
          white-space: pre-wrap;
          word-wrap: break-word;
          font-family: 'Courier New', Courier, monospace;
          font-size: 10pt;
          line-height: 1.5;
          color: #333;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #bdc3c7;
          text-align: center;
          font-size: 10px;
          color: #7f8c8d;
        }
        .confidential-notice {
          background: #fff3cd;
          border: 1px solid #ffc107;
          color: #856404;
          padding: 12px;
          margin-bottom: 20px;
          font-weight: bold;
          text-align: center;
          font-size: 11px;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="company-name">PentraCore International</div>
        <div class="company-tagline">Commodity Trade Facilitation</div>
      </div>

      <div class="confidential-notice">
        CONFIDENTIAL - For authorized recipients only
      </div>

      <div class="document-header">
        <div class="doc-type">${docType}</div>
        <div class="doc-meta">
          <div><span class="doc-meta-label">Deal Reference:</span> ${referenceNumber}</div>
          <div><span class="doc-meta-label">Generated:</span> ${today}</div>
          <div><span class="doc-meta-label">Document Type:</span> ${docType}</div>
        </div>
      </div>

      <div class="document-body">${escapeHtml(documentContent)}</div>

      <div class="footer">
        <p>Generated by PentraCore International | Confidential & Proprietary</p>
        <p>Unauthorized copying, distribution, or disclosure is strictly prohibited</p>
      </div>
    </body>
    </html>
  `

  const opt = {
    margin: [12, 10, 12, 10] as [number, number, number, number],
    filename: `${docType}-${today}.pdf`,
    image: { type: 'jpeg' as const, quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { orientation: 'portrait' as const, unit: 'mm' as const, format: 'a4' }
  }

  html2pdf().set(opt).from(htmlContent).save()
}

function escapeHtml(text: string): string {
  const map: { [key: string]: string } = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;'
  }
  return text.replace(/[&<>"']/g, (m) => map[m])
}
